import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const api = readFileSync(new URL('../src/api/technicalCollaborationTasks.js', import.meta.url), 'utf8')
const listPage = readFileSync(new URL('../src/views/collaboration/technical/index.vue', import.meta.url), 'utf8')
const detailPage = readFileSync(new URL('../src/pages/TechnicalCollaborationTaskPage.vue', import.meta.url), 'utf8')
const router = readFileSync(new URL('../src/router/index.js', import.meta.url), 'utf8')
const bomWorkspace = readFileSync(new URL('../src/components/TechnicalBomDraftWorkspace.vue', import.meta.url), 'utf8')
const packageWorkspace = readFileSync(new URL('../src/components/TechnicalPackageDraftWorkspace.vue', import.meta.url), 'utf8')
const priceWorkspace = readFileSync(new URL('../src/components/TechnicalPriceDraftWorkspace.vue', import.meta.url), 'utf8')

test('QCBP-09 routes carry taskId only and never accept user, OA, item or organization scope', () => {
  assert.match(api, /product-tasks\/mine/)
  assert.match(api, /product-tasks\/\$\{id\(taskId\)\}/)
  assert.match(api, /\$\{id\(taskId\)\}\/start/)
  assert.match(api, /\$\{id\(taskId\)\}\/validate/)
  assert.match(api, /\$\{id\(taskId\)\}\/submit/)
  assert.doesNotMatch(api, /oaNo|itemId|materialCode|businessUnitType|orgCode|userId/)
  assert.match(api, /product-tasks\/mine',\s*\{\s*suppressErrorToast:\s*true\s*\}/)
  assert.match(api, /product-tasks\/\$\{id\(taskId\)\}`,[^\n]*suppressErrorToast:\s*true/)
})

test('technical task list renders one explicit access state without leaking or duplicating errors', () => {
  assert.match(listPage, /当前账号没有技术协作权限/)
  assert.match(listPage, /你只能查看分配给自己的任务/)
  assert.match(listPage, /isDomainError\(error, 'TASK_ASSIGNEE_MISMATCH'\)/)
  assert.match(listPage, /showErrorOnce\(error, '本人任务加载失败'\)/)
  assert.doesNotMatch(listPage, /ElMessage\.error\(error\.message/)
})

test('technical task pages use server state and expose only meaningful task actions', () => {
  assert.match(listPage, /这里只显示你负责过的产品/)
  assert.match(listPage, /已提交任务仅供查看/)
  assert.match(listPage, /进入处理/)
  assert.match(detailPage, /开始处理/)
  assert.match(detailPage, /检查完整性/)
  assert.match(detailPage, /完成并提交财务审核/)
  assert.match(detailPage, /查看处理记录/)
  assert.match(detailPage, /数据从服务端保存/)
  assert.match(detailPage, /item\.required && !item\.completed/)
  assert.doesNotMatch(listPage, /localStorage/)
  assert.doesNotMatch(detailPage, /localStorage/)
})

test('technical task detail renders a stable assignee-only access state instead of a transient toast', () => {
  assert.match(detailPage, /当前账号不能查看此技术任务/)
  assert.match(detailPage, /协助者只能查看分配给自己的产品/)
  assert.match(detailPage, /isDomainError\(error, 'TASK_ASSIGNEE_MISMATCH'\)/)
  assert.match(detailPage, /v-if="accessDenied && !loading"/)
})

test('finance rejection is displayed as an actionable field-level reason to the technician', () => {
  assert.match(detailPage, /task\.returnIssues\?\.length/)
  assert.match(detailPage, /财务退回原因，请按下列内容修改后重新校验/)
  assert.match(detailPage, /issue\.itemTypeLabel/)
  assert.match(detailPage, /issue\.reason/)
})

test('QCBP-23 two technical menu entries filter one shared product-task model', () => {
  assert.match(listPage, /priceEntry/)
  assert.match(listPage, /route\.path\.endsWith\('\/prices'\)/)
  assert.match(listPage, /item\.primaryScope !== 'PRICE_ONLY'/)
  assert.match(listPage, /item\.openGapCount/)
  assert.match(listPage, /BOM、包装和价格共用一个任务/)
})

test('authenticated detail route and collaborator landing share the same task pages', () => {
  assert.match(router, /path: '\/collaboration\/product-tasks\/:taskId'/)
  assert.match(router, /activeMenu: '\/collaboration\/tasks'/)
  assert.match(router, /OA_COLLABORATOR/)
  assert.match(router, /TECHNICAL_TASK_LIST_PATH = '\/collaboration\/tasks'/)
  assert.match(router, /path: TECHNICAL_TASK_LIST_PATH/)
})

test('QCBP-10 presents exactly three business steps and one primary action per active step', () => {
  assert.match(bomWorkspace, /找参考BOM/)
  assert.match(bomWorkspace, /编辑并导出完整BOM/)
  assert.match(bomWorkspace, /电子图库录入并校验/)
  assert.match(bomWorkspace, /复制选中BOM/)
  assert.match(bomWorkspace, /applyDraft\(draft, false\)/)
  assert.match(bomWorkspace, /applyDraft\(draft, true\)/)
  assert.match(bomWorkspace, /保存并检查完整BOM/)
  assert.match(bomWorkspace, /!workspace\.value\?\.target\?\.materialNature/)
  assert.match(bomWorkspace, /请选择当前产品自己的物料性质/)
  assert.doesNotMatch(bomWorkspace, /步骤4|第四步|接口步骤/)
})

test('QCBP-10 tree editor supports required safe operations and server persistence', () => {
  assert.match(bomWorkspace, /加下级/)
  assert.match(bomWorkspace, /加同级/)
  assert.match(bomWorkspace, /编辑\/替换/)
  assert.match(bomWorkspace, /删除整枝/)
  assert.match(bomWorkspace, /更多操作/)
  assert.match(bomWorkspace, /handleNodeCommand/)
  assert.match(bomWorkspace, /:default-expanded-keys="defaultExpandedKeys"/)
  assert.doesNotMatch(bomWorkspace, /default-expand-all\s+\n\s+:expand-on-click-node/)
  assert.match(bomWorkspace, /只看变更/)
  assert.match(bomWorkspace, /上移/)
  assert.match(bomWorkspace, /下移/)
  assert.match(bomWorkspace, /saveTechnicalBomDraft/)
  assert.match(bomWorkspace, /flatNodes/)
  assert.doesNotMatch(bomWorkspace, /localStorage/)
  assert.match(detailPage, /async function handleBomUpdated\(\) \{\s*await load\(\)/)
  assert.match(bomWorkspace, /function natureTag\(value\)[\s\S]*return undefined/)
  assert.doesNotMatch(bomWorkspace, /function natureTag\(value\)[^\n]*: ''/)
})

test('QCBP-10 search and copy API never accept organization or technician scope from client', () => {
  assert.match(api, /bom-candidates/)
  assert.match(api, /bom-draft\/copy/)
  assert.match(api, /bom-draft\/new/)
  assert.match(api, /bom-draft`/)
  assert.doesNotMatch(api, /priceOrgCode|materialOrganizationCode|technicianUserId|businessUnitType/)
})

test('QCBP-11 template export and verification are server-authoritative', () => {
  assert.match(api, /bom-draft\/export-electronic-template/)
  assert.match(api, /electronic-bom\/verify/)
  assert.match(api, /body: \{ expectedVersion, bomPurpose \}/)
  assert.doesNotMatch(api, /completed|verified\s*:|valid\s*:|success\s*:/)
  assert.match(api, /content-type/)
  assert.match(api, /application\/json/)
  assert.match(api, /电子图库BOM模板下载失败/)
})

test('QCBP-11 third step explains the only three human actions and exposes one completion action', () => {
  assert.match(bomWorkspace, /3\. 在电子图库录入并回取校验/)
  assert.match(bomWorkspace, /下载电子图库BOM模板/)
  assert.match(bomWorkspace, /到电子图库录入/)
  assert.match(bomWorkspace, /回到这里校验/)
  assert.match(bomWorkspace, /我已录入，回取并校验/)
  assert.match(bomWorkspace, /系统自行查询电子图库，前端不能手工标记完成/)
  assert.match(bomWorkspace, /workspace\.verificationIssues/)
  assert.match(bomWorkspace, /verifyTechnicalElectronicBom/)
  assert.match(bomWorkspace, /if \(result\.verified\) await load\(\)/)
  assert.doesNotMatch(bomWorkspace, /上传校验结果|手工标记成功|跳过校验/)
})

test('QCBP-12 package workspace keeps U9 body read-only and supports both approved sources', () => {
  assert.match(packageWorkspace, /U9 本体保持原样/)
  assert.match(packageWorkspace, /参考已审核报价产品/)
  assert.match(packageWorkspace, /按包装目件查找/)
  assert.match(packageWorkspace, /复制并开始修改/)
  assert.match(packageWorkspace, /不会修改参考记录/)
  assert.match(detailPage, /TechnicalPackageDraftWorkspace/)
  assert.doesNotMatch(packageWorkspace, />编辑本体<|>保存U9<|>上传BOM</)
})

test('QCBP-12 package draft reloads server state and has one clear price-check action', () => {
  assert.match(api, /'package-parents'/)
  assert.match(api, /'reference-products'/)
  assert.match(api, /\/package\/\$\{path\}/)
  assert.match(api, /package-draft\/copy/)
  assert.match(api, /method: 'PUT'/)
  assert.match(api, /package-draft\/check-price/)
  assert.match(packageWorkspace, /保存并检查价格/)
  assert.match(packageWorkspace, /fetchTechnicalPackageWorkspace/)
  assert.doesNotMatch(packageWorkspace, /localStorage/)
  assert.doesNotMatch(api, /package.*businessUnitType|package.*priceOrgCode|package.*technicianUserId/)
})

test('QCBP-13 true price gaps show exact BOM position, quantity, month and organization', () => {
  assert.match(detailPage, /BOM位置与用量/)
  assert.match(detailPage, /row\.bomPath/)
  assert.match(detailPage, /row\.bomQuantity/)
  assert.match(detailPage, /row\.bomUnit/)
  assert.match(detailPage, /row\.accountingMonth/)
  assert.match(detailPage, /row\.applicableOrgCode/)
  assert.match(detailPage, /为什么要处理/)
})

test('QCBP-14 formal price copy and direct draft lifecycle stays server-authoritative', () => {
  assert.match(api, /price-gaps\/\$\{id\(gapId\)\}\/formal-prices/)
  assert.match(api, /draft\/copy/)
  assert.match(api, /draft\/direct/)
  assert.match(api, /price-drafts\/\$\{id\(draftId\)\}/)
  assert.match(api, /price-drafts\/\$\{id\(draftId\)\}\/validate/)
  assert.match(priceWorkspace, /保存并校验/)
  assert.match(priceWorkspace, /validationStatus/)
  assert.match(api, /change-reference/)
  assert.match(detailPage, /TechnicalPriceDraftWorkspace/)
  assert.match(priceWorkspace, /优先复制正式有效记录/)
  assert.match(priceWorkspace, /找不到合适记录/)
  assert.match(priceWorkspace, /查看\/修改/)
  assert.match(priceWorkspace, /草稿已保存/)
  assert.match(priceWorkspace, /重新打开会继续编辑这一份/)
  assert.match(priceWorkspace, /原参考快照已保留/)
  assert.doesNotMatch(priceWorkspace, /localStorage|演示草稿|模拟价格/)
  assert.doesNotMatch(api, /price.*businessUnitType|price.*orgCode|price.*technicianUserId/)
})

test('QCBP-16 linked price copies formula structure but requests only referenced target variables', () => {
  assert.match(priceWorkspace, /公式可以从相似正式记录复制并修改/)
  assert.match(priceWorkspace, /系统行情变量自动取值/)
  assert.match(priceWorkspace, /只要求填写公式实际引用的本料号技术参数/)
  assert.match(priceWorkspace, /displayFields/)
  assert.match(priceWorkspace, /!\['BINDING', 'RANGE_ROW'\]\.includes\(field\.sectionCode\)/)
  assert.match(priceWorkspace, /field\.fieldCode !== 'FORMULA_EXPR_CN'/)
  assert.match(priceWorkspace, /isFormulaField/)
  assert.match(priceWorkspace, /只允许使用系统已登记变量和四则运算/)
  assert.match(priceWorkspace, /isValidatableDraft/)
  assert.match(priceWorkspace, /保存并校验/)
  assert.match(priceWorkspace, /系统不会展示试算金额/)
  assert.doesNotMatch(priceWorkspace, />试算结果<|>当前取价金额</)
})

test('all validated price gaps clearly lead the technician to completeness validation', () => {
  assert.match(priceWorkspace, /pendingValidationCount/)
  assert.match(priceWorkspace, /allValidatedHint/)
  assert.match(priceWorkspace, /下一步请点击页面底部“检查完整性”/)
  assert.match(priceWorkspace, /下一步请点击页面底部“完成并提交财务审核”/)
  assert.match(detailPage, /:next-action="task\.nextAction"/)
})

test('QCBP-17 range price edits one complete group with explicit boundaries and server validation', () => {
  assert.match(priceWorkspace, /整组维护区间价/)
  assert.match(priceWorkspace, /每段下限包含、上限不包含/)
  assert.match(priceWorkspace, /最后一段上限可留空表示无穷/)
  assert.match(priceWorkspace, /当前报价数量必须且只能命中一段/)
  assert.match(priceWorkspace, /新增区间/)
  assert.match(priceWorkspace, /deleteRangeRow/)
  assert.match(priceWorkspace, /RANGE_LOW/)
  assert.match(priceWorkspace, /RANGE_HIGH/)
  assert.match(priceWorkspace, /PRICE_EXCL_TAX/)
  assert.match(priceWorkspace, /PRICE_INCL_TAX/)
  assert.match(priceWorkspace, /isRangeDraft/)
  assert.match(priceWorkspace, /isValidatableDraft/)
  assert.match(priceWorkspace, /保存并校验/)
  assert.doesNotMatch(priceWorkspace, /区间试算金额|预计成本|模拟命中/)
})
